
 



//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-10-31 21:47:20 by 马佳斌
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Learn.Data;
using Learn.Data.Context;
using Learn.IData;

namespace Learn.DataFactory
{	
   public partial class DBSession : IDBSession
    {

	   public I__MigrationHistoryRepository __MigrationHistoryRepository
	   {
	        get
           {
              return new __MigrationHistoryRepository();
           }
	    }  
	
	 
	   public IDepartmentRepository DepartmentRepository
	   {
	        get
           {
              return new DepartmentRepository();
           }
	    }  
	
	 
	   public IEmployeeRepository EmployeeRepository
	   {
	        get
           {
              return new EmployeeRepository();
           }
	    }  
	
	 
	   public IEmpRoleRelationshipRepository EmpRoleRelationshipRepository
	   {
	        get
           {
              return new EmpRoleRelationshipRepository();
           }
	    }  
	
	 
	   public IPermissionRepository PermissionRepository
	   {
	        get
           {
              return new PermissionRepository();
           }
	    }  
	
	 
	   public IRoleRepository RoleRepository
	   {
	        get
           {
              return new RoleRepository();
           }
	    }  
	
	 
	   public IRolePerRelationshipRepository RolePerRelationshipRepository
	   {
	        get
           {
              return new RolePerRelationshipRepository();
           }
	    }  
	
	 
	   public IsysdiagramsRepository sysdiagramsRepository
	   {
	        get
           {
              return new sysdiagramsRepository();
           }
	    }  
	
	 
	   public IVipPermssionRepository VipPermssionRepository
	   {
	        get
           {
              return new VipPermssionRepository();
           }
	    }  
	
	 	   }

   
}



