//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-11-12 19:35:30 by 马佳斌
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Learn.Core.Domain;
using Learn.IService;


namespace Learn.Service
 {	
	   public partial class DepartmentService:BaseService<Department>,IDepartmentService
	    {
			public override void SetCurrentDal()
           {
            CurrentService = dbSession.DepartmentRepository;
            }

	       
	    }

		

	 		
		  
 }
