//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-10-30 12:33:55 by 马佳斌
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



using System;
namespace Learn.Core
{	

	public partial class Act_ActivityParticipator
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public Guid ParticipatorID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ActivityID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string StoreCode { get; set; }
		
		/// <summary>
		/// '1'为所有门店都参与，‘0’为指定门店参与
		/// </summary>		
		public int? IsAllParticipator { get; set; }
		 
    }
	
	   
	 		 
    }
