//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-10-30 12:33:55 by 马佳斌
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



using System;
namespace Learn.Core
{	

	public partial class Import_StoreInfo
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public int DetailID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? TaskID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public short? Status { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Remark { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string StoreCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string StoreName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string DealerName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ClientOrganizationName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string StoreType { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string StoreNature { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ChannelType { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string IsSRStore { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Region { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ProvinceName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CityName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Address { get; set; }
		 
    }
	
	   
	 		 
    }
