//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-10-30 12:33:55 by 马佳斌
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



using System;
namespace Learn.Core
{	

	public partial class KS_TestPaper
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public Guid TestPaperID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public Guid CoursesID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string TestPaperName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public short? TestPaperType { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string TestPaperDesc { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? TotalQuantity { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal? TotalScore { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal? PassedScore { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? MaxCount { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? MaxTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? Status { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public short? ObjectID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool? IsDelete { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? CreatedUserID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? CreatedDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? UpdatedUserID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? UpdatedDate { get; set; }
		 
    }
	
	   
	 		 
    }
