//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-10-30 12:33:55 by 马佳斌
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



using System;
namespace Learn.Core
{	

	public partial class KS_UserExamResult
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public Guid ResultID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public Guid? UserExamID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public Guid QuestionID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string QuestionName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public short? QuestionType { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string UserAnswer { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal UserScore { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string QuestionAnswer { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal QuestionScore { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool? IsDelete { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? CreatedUserID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? CreatedDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? UpdatedUserID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? UpdatedDate { get; set; }
		 
    }
	
	   
	 		 
    }
