//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-10-30 12:33:55 by 马佳斌
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



using System;
namespace Learn.Core
{	

	public partial class Log_BusinessOperate
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public long BizLogID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ModuleName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string MethodName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string TargetID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Action { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string LoginName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? CreateTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ServerName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ClientIP { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string PageUrl { get; set; }
		 
    }
	
	   
	 		 
    }
