//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-10-30 12:33:55 by 马佳斌
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



using System;
namespace Learn.Core
{	

	public partial class Passport_Ticket
    {
		
		/// <summary>
		/// APP_SIGNIN_ID
		/// </summary>		
		public string APP_SIGNIN_ID { get; set; }
		
		/// <summary>
		/// SIGNIN_ID
		/// </summary>		
		public string SIGNIN_ID { get; set; }
		
		/// <summary>
		/// APP_ID
		/// </summary>		
		public string APP_ID { get; set; }
		
		/// <summary>
		/// APP_SIGNIN_TIME
		/// </summary>		
		public DateTime APP_SIGNIN_TIME { get; set; }
		
		/// <summary>
		/// APP_SIGNIN_TIMEOUT
		/// </summary>		
		public DateTime? APP_SIGNIN_TIMEOUT { get; set; }
		
		/// <summary>
		/// APP_SIGNIN_URL
		/// </summary>		
		public string APP_SIGNIN_URL { get; set; }
		
		/// <summary>
		/// APP_SIGNIN_IP
		/// </summary>		
		public string APP_SIGNIN_IP { get; set; }
		
		/// <summary>
		/// APP_LOGOFF_URL
		/// </summary>		
		public string APP_LOGOFF_URL { get; set; }
		
		/// <summary>
		/// DEL_FLAG
		/// </summary>		
		public string DEL_FLAG { get; set; }
		 
    }
	
	   
	 		 
    }
