//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-10-30 12:33:55 by 马佳斌
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



using System;
namespace Learn.Core
{	

	public partial class Passport_Signin_Info
    {
		
		/// <summary>
		/// SIGNIN_ID
		/// </summary>		
		public string SIGNIN_ID { get; set; }
		
		/// <summary>
		/// SORT_ID
		/// </summary>		
		public int SORT_ID { get; set; }
		
		/// <summary>
		/// SIGNIN_TIME
		/// </summary>		
		public DateTime SIGNIN_TIME { get; set; }
		
		/// <summary>
		/// SIGNIN_TIMEOUT
		/// </summary>		
		public DateTime? SIGNIN_TIMEOUT { get; set; }
		
		/// <summary>
		/// USER_ID
		/// </summary>		
		public string USER_ID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string USER_NAME { get; set; }
		
		/// <summary>
		/// DOMAIN
		/// </summary>		
		public object DOMAIN { get; set; }
		
		/// <summary>
		/// AUTHENTICATE_SERVER
		/// </summary>		
		public object AUTHENTICATE_SERVER { get; set; }
		 
    }
	
	   
	 		 
    }
