//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-10-30 12:33:55 by 马佳斌
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



using System;
namespace Learn.Core
{	

	public partial class Res_LearnCourses
    {
		
		/// <summary>
		/// 已学习课程的主键id
		/// </summary>		
		public Guid CoursesID { get; set; }
		
		/// <summary>
		/// 用户id
		/// </summary>		
		public int UserID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? LearnTime { get; set; }
		 
    }
	
	   
	 		 
    }
