//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-10-30 12:33:55 by 马佳斌
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



using System;
namespace Learn.Core
{	

	public partial class Res_Courses
    {
		
		/// <summary>
		/// 课程id
		/// </summary>		
		public Guid CoursesID { get; set; }
		
		/// <summary>
		/// 课程类别
		/// </summary>		
		public int? CoursesTypeID { get; set; }
		
		/// <summary>
		/// 课程图片
		/// </summary>		
		public string CoursesIcon { get; set; }
		
		/// <summary>
		/// 课程名称
		/// </summary>		
		public string CoursesName { get; set; }
		
		/// <summary>
		/// 课程内容
		/// </summary>		
		public string CoursesContext { get; set; }
		
		/// <summary>
		/// 对应积分
		/// </summary>		
		public int? Integral { get; set; }
		
		/// <summary>
		/// 状态
		/// </summary>		
		public short? State { get; set; }
		
		/// <summary>
		/// 创建人
		/// </summary>		
		public string Creator { get; set; }
		
		/// <summary>
		/// 创建时间
		/// </summary>		
		public DateTime? CreatedTime { get; set; }
		
		/// <summary>
		/// 课程关键字
		/// </summary>		
		public string KeyWord { get; set; }
		 
    }
	
	   
	 		 
    }
