//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-10-31 21:47:21 by 马佳斌
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Learn.Core.Domain
{	
	public partial class Role
    {
		
        /// <summary>
		/// 
		/// </summary>		
		public int RoleId { get; set; }
		
        /// <summary>
		/// 
		/// </summary>		
		public int RoleDepId { get; set; }
		
        /// <summary>
		/// 
		/// </summary>		
		public string RoleName { get; set; }
		
        /// <summary>
		/// 
		/// </summary>		
		public bool RoleIsDel { get; set; }
		
        /// <summary>
		/// 
		/// </summary>		
		public DateTime RoleAddTime { get; set; }
		 
    }
	
	     
}
