//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-10-30 12:33:55 by 马佳斌
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



using System;
namespace Learn.Core
{	

	public partial class saleinfo
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public Guid uid { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string storecode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string srcode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string buytime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string mobiletel { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string edc { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string skucode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string skudesc { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string brand { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string stage { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string package { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string factor { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string buycount { get; set; }
		 
    }
	
	   
	 		 
    }
