//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-10-30 12:33:55 by 马佳斌
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



using System;
namespace Learn.Core
{	

	public partial class Site_MemberPurchaseHistory
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public Guid PurchaseHistoryID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string StoreCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ActivityID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string OpenID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string MerchandiseCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal? SpendingAmount { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? PurchaseNumber { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? PurchaseDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Auditor { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? AuditState { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? AuditTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? Flag { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Message { get; set; }
		 
    }
	
	   
	 		 
    }
