//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-10-30 12:33:55 by 马佳斌
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



using System;
namespace Learn.Core
{	

	public partial class Site_StoreSRIndex
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public int IndexID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string StoreCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? Years { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? Months { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? IndexNumber { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CompletionProportion { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? State { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Creator { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? CreateTime { get; set; }
		 
    }
	
	   
	 		 
    }
