//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-10-30 12:33:55 by 马佳斌
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



using System;
namespace Learn.Core
{	

	public partial class Site_PageURL
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public int PageID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? FunctionID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string PageURL { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public short? State { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? IsMainPage { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Description { get; set; }
		 
    }
	
	   
	 		 
    }
