//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-10-30 12:33:55 by 马佳斌
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



using System;
namespace Learn.Core
{	

	public partial class Site_Order
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public string OrderCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? UserID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string OrderName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? OrderTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? State { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ExpressCompany { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string WaybillNumber { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Address { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? PaymentTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public short? IsValid { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Remark { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? DeliveryDate { get; set; }
		 
    }
	
	   
	 		 
    }
