//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-10-30 12:33:55 by 马佳斌
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



using System;
namespace Learn.Core
{	

	public partial class Site_User
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public int UserID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string LoginName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Password { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string WeChatOpenid { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? UserCategory { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string UserName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string PhotoUrl { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? OrganizationID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string StoreCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? Sex { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? Birthday { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string OfficeTelphone { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string MobilePhone { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Hobby { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string TwoDimensionCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? IntegralCount { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public Guid? GradeID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public short? State { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Creator { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? CreatedTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Modifier { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? ModifiedTime { get; set; }
		 
    }
	
	   
	 		 
    }
