//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-10-30 12:33:55 by 马佳斌
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



using System;
namespace Learn.Core
{	

	public partial class Site_Grade
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public Guid GradeID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string GradeName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? GradeLevel { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? InitialGrowthValue { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? EndGrowthValue { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public short? State { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Creator { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? CreateTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Modifier { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? ModifiedTime { get; set; }
		 
    }
	
	   
	 		 
    }
