//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-10-30 12:33:55 by 马佳斌
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



using System;
namespace Learn.Core
{	

	public partial class Site_SignIn
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public Guid SignInID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? UserID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? SignInDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? OpenStoreSignInTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? OpenStoreMood { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? ClosedStoreSiggnInTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? ClosedStoreMood { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string EveryDayShare { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public TimeSpan? ShareTime { get; set; }
		 
    }
	
	   
	 		 
    }
