//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-10-30 12:33:55 by 马佳斌
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



using System;
namespace Learn.Core
{	

	public partial class Site_MemberInfo
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public string OpenID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string StoreCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Wechat { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? MemberType { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool? IsMiniature { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime RecruitmentDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string MobilePhone { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string MemberName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? BabyDateOfBirth { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? AgeOfTheMoon { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? GestationAge { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string AlCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? AlCodeValid { get; set; }
		 
    }
	
	   
	 		 
    }
