//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-10-30 12:33:55 by 马佳斌
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



using System;
namespace Learn.Core
{	

	public partial class Site_RewardRegular
    {
		
		/// <summary>
		/// 对应《字典项表》字段
		/// </summary>		
		public Guid RewardRegularID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? RewardType { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string RegularName { get; set; }
		
		/// <summary>
		/// 对应页面操作后查询指定积分
		/// </summary>		
		public string Action { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? RewardMeans { get; set; }
		
		/// <summary>
		/// 奖励的触发间隔，以天为单位(0-仅触发一次，1-一天一次，7-7天一次)
		/// </summary>		
		public int? RewardFrequency { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? PewardValue { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Creator { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? CreateTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Modifier { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? ModifiedTime { get; set; }
		 
    }
	
	   
	 		 
    }
