//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-10-30 12:33:55 by 马佳斌
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



using System;
namespace Learn.Core
{	

	public partial class Site_CommonAddress
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public Guid CommonAddressID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? UserID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Consignee { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Phone { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ProvinceCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CityCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string AreaCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Address { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool? IsDefaultAddress { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Creator { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? CreatedTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Modifier { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? ModifiedTime { get; set; }
		 
    }
	
	   
	 		 
    }
