//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-10-30 12:33:55 by 马佳斌
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



using System;
namespace Learn.Core
{	

	public partial class SRRecruitmentMember
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public Guid SynchronizationID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string StoreCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string IsSRStore { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Brand { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string SRCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string SRNewStudent { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string SRSeniorStudent { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string LoginName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string StoreManagerStudetnt { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string StoreManagerSeniorStudent { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? RecruitmentDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? SynchronizationDate { get; set; }
		 
    }
	
	   
	 		 
    }
