//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-10-30 12:33:55 by 马佳斌
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



using System;
namespace Learn.Core
{	

	public partial class Supply_PurchasingOrder
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public string PurchasingOrderCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string PurchasingOrderName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? PurchasingTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string StoreCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? UserID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? State { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public short? IsValid { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public short? AuditState { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? AuditTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Auditor { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string AuditOpinion { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ExpressCompany { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string WaybillNumber { get; set; }
		 
    }
	
	   
	 		 
    }
