//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-10-30 12:33:55 by 马佳斌
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



using System;
namespace Learn.Core
{	

	public partial class Supply_InventoryCalibration
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public Guid MerchandiseInventoryID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string StoreCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string MerchandiseCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string MerchandiseUnit { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Stage { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int Grams { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? InventoryNumber { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Creator { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? CreateTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? CalibrationNumbner { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? State { get; set; }
		 
    }
	
	   
	 		 
    }
