//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-10-30 12:33:55 by 马佳斌
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



using System;
namespace Learn.Core
{	

	public partial class Supply_Merchandise
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public string MerchandiseCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string BrandCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string MerchandiseName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string MerchandiseIcon { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string MerchandiseUnit { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal? UnitPrice { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Stage { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? Grams { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public short? State { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string MerchandiseDesc { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public decimal? Factor { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? Sorting { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Creator { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? CreateTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Modifier { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? ModifiedTime { get; set; }
		 
    }
	
	   
	 		 
    }
