//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-10-30 12:33:55 by 马佳斌
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



using System;
namespace Learn.Core
{	

	public partial class Sys_NotifyTemplate
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public Guid TemplateID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Category { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string TitleTemplate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ContentTemplate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Remark { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public short State { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Creator { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Modifier { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? ModifiedTime { get; set; }
		 
    }
	
	   
	 		 
    }
