//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-10-30 12:33:55 by 马佳斌
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



using System;
namespace Learn.Core
{	

	public partial class Sys_NotifySend
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public Guid NotifyID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int NotifyTypeID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Title { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Context { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Sender { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? SendeTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public short? State { get; set; }
		 
    }
	
	   
	 		 
    }
