//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-10-30 12:33:55 by 马佳斌
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



using System;
namespace Learn.Core
{	

	public partial class Sys_City
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public string CityCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string CityName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ProvinceCode { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool? IsUse { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? OrderNum { get; set; }
		 
    }
	
	   
	 		 
    }
