//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-11-12 19:31:24 by 马佳斌
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



using System;
namespace WebForm
{	

	public partial class __MigrationHistory
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public string MigrationId { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ContextKey { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public byte[] Model { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ProductVersion { get; set; }
		 
    }
	
	   
	 		 
    }
