//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-10-30 12:42:38 by 马佳斌
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



using System;
namespace WebForm
{	

	public partial class Employee
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public int EmpId { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int EmpDepId { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string EmpCnName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string EmpLoginName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string EmpLoginPwd { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool EmpSex { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool EmpAge { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string EmpCellPhone { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string EmpPhone { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string EmpAddress { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool EmpIsDel { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime EmpAddTime { get; set; }
		 
    }
	
	   
	 		 
    }
