//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-10-31 21:47:21 by 马佳斌
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



using System;
namespace WebForm
{	

	public partial class Permission
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public int PerId { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int PerParent { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string PerName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string PerRemark { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string PerAreaName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string PerContorllerName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string PerActionName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string PerFormMethod { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int PerOperationType { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string PerJsMethodName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string PerIco { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool PerIsLink { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int PerOrder { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool PerIsShow { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public bool PerIsDel { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime PerAddTime { get; set; }
		 
    }
	
	   
	 		 
    }
